name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PR
        uses: pascalgn/automerge-action@v0.15.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
